### ISSUE TITLE
Issue deploying Dynamo/Elixir to Heroku with buildpack

### ISSUE THREAD

**Issue by Tonkpils** [goshacmd/heroku-buildpack-elixir#3]
Long story short, it seems the buildpack is storing the dynamo apps in the `/app/ebin` directory. According to OTP the app should be stored in a directory with the app's name: `/my_app_name/ebin`.

Here's the long story: https://github.com/elixir-lang/elixir/issues/1046

**Comment by guilleiguaran** [comment]
I'm having same problem, looks like by default Heroku store apps in `/app` folder then we need to modify the buildpack to save it to `/app/my_app_name/ebin`

**Comment by Tonkpils** [comment]
I would love to help out, I'm not too knowledgeable with the buildpack process or shell scripting. With that in mind I would be glad to do this with some guidance.

**Comment by goshacmd** [comment]
`bin/compile` is probably the place to move the app itself into `/app/xxx` before installing deps.

**Comment by guilleiguaran** [comment]
@goshakkk @Tonkpils I'm working on this, I'll open a PR with my current progress

**Comment by guilleiguaran** [comment]
#5

**Comment by guilleiguaran** [comment]
I think this can be closed now :smile:

**Comment by goshacmd** [comment]
Right.

**Comment by guilleiguaran** [comment]
@Tonkpils can you confirm that the issue is fixed for you?

**Comment by Tonkpils** [comment]
@guilleiguaran Does anything need to be modified from the Procfile? I'm currently getting this exception deploying 

```
-----> Compiling app
       Compiled lib/sparky.ex
       Compiled lib/sparky/models/user.ex
       Compiled lib/sparky/dynamo.ex
       ** (ArgumentError) argument error: nil
           /tmp/build_yefdgf1v9hxd/sparky/deps/dynamo/lib/mix/tasks/compile.dynamo.ex:67: Mix.Tasks.Compile.Dynamo.do_compile/3
           /tmp/build_yefdgf1v9hxd/ex/lib/elixir/lib/enum.ex:1515: Enumerable.List.reduce/3
           /tmp/build_yefdgf1v9hxd/ex/lib/elixir/lib/enum.ex:292: Enum."-each/2-lists^foreach/1-0-"/2
           /tmp/build_yefdgf1v9hxd/ex/lib/elixir/lib/enum.ex:292: Enum.each/2
           /tmp/build_yefdgf1v9hxd/ex/lib/mix/lib/mix/tasks/compile.ex:76: Mix.Tasks.Compile.run/1
           /tmp/build_yefdgf1v9hxd/ex/lib/mix/lib/mix/project.ex:174: Mix.Project.recur/2
           /tmp/build_yefdgf1v9hxd/ex/lib/mix/lib/mix/task.ex:167: Mix.Task.run/2
           /tmp/build_yefdgf1v9hxd/ex/lib/mix/lib/mix/cli.ex:38: Mix.CLI.run_task/2
```

**Comment by guilleiguaran** [comment]
@Tonkpils, no you don't need to change anything in your Procfile

I think your issue maybe caused by a mismatch between the version of Dynamo used to build the app and the version of Elixir that is being used to compile it (Elixir master is used by default if you don't set a version in `.preferred_elixir_version`)

I just tested with a new app (generated with Elixir master and Dynamo master) and it works as expected.

**Comment by Tonkpils** [comment]
@guilleiguaran I had a `.preferred_otp_version` specified to `OTP_R16B` I removed that file and I'm getting the following error. 

```
2013-07-24T18:36:19.338569+00:00 heroku[web.1]: Starting process with command `MIX_ENV=prod mix server -p 26783`
2013-07-24T18:36:21.055980+00:00 app[web.1]: {"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

I wasn't specifying a `.preferred_elixir_version`. The Dynamo documentation says to specify a erlang/elixir version. I'm trying to reproduce this with a new app with Elixir master and Dynamo master. Might be that I used an old version of Dynamo to create the sparky app.

**Comment by Tonkpils** [comment]
This is the output I'm getting from a brand new app 

```
git push heroku master                                                             
Counting objects: 28, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (21/21), done.
Writing objects: 100% (28/28), 4.49 KiB | 0 bytes/s, done.
Total 28 (delta 0), reused 0 (delta 0)

-----> Fetching custom git buildpack... done
-----> Elixir app detected
-----> Using Erlang/OTP master
-------> Fetching Erlang/OTP master
-------> Unpacking Erlang/OTP master
-------> Installing Erlang/OTP master

-----> Installing Rebar from buildpack
-----> Using Elixir master
-------> Fetching Elixir master
-------> Unpacking Elixir master
-------> Installing Elixir master
make: *** [erlang] Error 1
-----> Building with Mix
-----> Bundling dependencies
       {"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

       Crash dump was written to: erl_crash.dump
       init terminating in do_boot ()
-----> Compiling app
       {"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

       Crash dump was written to: erl_crash.dump
       init terminating in do_boot ()
-----> Discovering process types
       Procfile declares types -> (none)

-----> Compiled slug size: 44.2MB
-----> Launching... done, v5
       http://sparkler-elixir.herokuapp.com deployed to Heroku
```

**Comment by Tonkpils** [comment]
@guilleiguaran Specifying the `.preferred_otp_version` to `OTP_R16B` fixed that issue. Seems something in erlang master is causing that issue. As for the Elixir it seems to be working! :+1:

**Comment by guilleiguaran** [comment]
@Tonkpils ah right, I forget to mention that I was using R16B locally and in Heroku

Thanks for confirming that this is working!!!
